Gtech
Somanasi/somanasi_app_ui pull request #33
Opened 2023-06-18 19:38 UTC by michaeldouglasvg

Paullaster

2023-06-19 02:22 UTC, paullaster requested changes
Check on that and let know if you may need my help

2023-06-19 02:22 UTC, paullaster commented on index.html
why are we modifying this file? <body>

2023-06-19 02:22 UTC, paullaster commented on src/modules/dashboard/components/layouts/Sidebar.jsx
What is you handle this state as dashboard global?

2023-06-24 08:24 UTC, michaeldouglasvg commented on index.html
There is changes due to responsiveness and layout.

2023-06-24 08:26 UTC, michaeldouglasvg commented on index.html
Due to responsive changes and layout.

2023-06-24 08:28 UTC, michaeldouglasvg commented on src/modules/dashboard/components/layouts/Sidebar.jsx
I havent created the use context of the dashboard. Will review the chnages and make this effective. Have been dealing with layout and navigation...since have figured out. Have started the constext.

2023-06-24 09:40 UTC, paullaster commented
Noted on this.
We'll merge it tomorrow during our stand up

On Sat, Jun 24, 2023, 11:28 Michael Douglas ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On src/modules/dashboard/components/layouts/Sidebar.jsx
> <https://github.com/Somanasi/somanasi_app_ui/pull/33#discussion_r1240640416>
> :
>
> I havent created the use context of the dashboard. Will review the chnages
> and make this effective. Have been dealing with layout and
> navigation...since have figured out. Have started the constext.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Somanasi/somanasi_app_ui/pull/33#discussion_r1240640416>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKLO5S3DKMRLPKDNIHIT5ODXM2QKFANCNFSM6AAAAAAZLCPQN4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-07-01 15:11 UTC, paullaster approved these changes
Code Reviewed.
Few recommendations for few changes to be assigned to another engineer

2023-07-01 15:13 UTC, merged